'use strict';
const $=s=>document.querySelector(s), cats=['Hlavní jídla','Polévky','Pečení a dezerty','Snídaně a svačiny','Saláty a přílohy','Zavařování','Ostatní'];
let db,recipes=[],draftPhotos=[],draftScan='',editing=null,selected=null,busy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3500)}
function tx(mode,action){return new Promise((resolve,reject)=>{const t=db.transaction('recipes',mode),s=t.objectStore('recipes');let r;try{r=action(s)}catch(e){t.abort();reject(e);return}t.oncomplete=()=>resolve(r?.result);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error||Error('Ukládání přerušeno'))})}
async function refresh(){recipes=await tx('readonly',s=>s.getAll());render()}
function render(){const q=$('#search').value.toLocaleLowerCase('cs'),cat=$('#filter').value,rows=recipes.filter(r=>(!cat||r.category===cat)&&[r.title,r.ingredients,r.notes].join(' ').toLocaleLowerCase('cs').includes(q)).sort((a,b)=>b.updated-a.updated);$('#count').textContent=recipes.length?`${recipes.length} receptů · Vyzkoušeno, uvařeno, uloženo.`:'Tvoje recepty. Tvoje fotky. Přesně podle tvé chuti.';renderTabs();$('#recipes').innerHTML=rows.length?rows.map(r=>`<button class="card" data-category="${cats.indexOf(r.category)}" data-id="${esc(r.id)}">${r.photos[0]?`<img class="cover" src="${esc(r.photos[0])}" alt="${esc(r.title)}">`:`<div class="textcover" aria-hidden="true">${esc(r.title.slice(0,1))}</div>`}<div class="cardbody"><span class="meta">${esc(r.category)}</span><h2>${esc(r.title)}</h2><div class="cardfoot"><span>${r.servings} porcí</span><span class="openrecipe">Otevřít ↗</span></div></div></button>`).join(''):(recipes.length?`<div class="empty search-empty"><span class="eyebrow">HLEDÁNÍ</span><h2>Tenhle recept tu není.</h2><p>Zkus jinou surovinu nebo kategorii.</p></div>`:`<div class="empty welcome"><div class="welcome-copy"><span class="eyebrow">TVÁ KUCHAŘKA ZAČÍNÁ TADY</span><h2>Tohle si zaslouží<br><em>uvařit znovu.</em></h2><p>Babiččin koláč. Nedělní oběd. Nebo tvůj vlastní experiment, který se povedl.</p><button id="emptyNew">＋ Uložit první recept</button><span class="welcome-note">Ručně nebo z fotky kuchařky.</span></div><div class="welcome-photo"><img src="kitchen.jpg" alt="Těstoviny s rajčaty a čerstvou bazalkou" width="1200" height="800"><span class="photo-stamp">DOMA<br>CHUTNÁ<br><em>nejlíp.</em></span></div></div>`);$('#emptyNew')?.addEventListener('click',()=>openEditor());document.querySelectorAll('.card').forEach(b=>b.onclick=()=>showDetail(b.dataset.id))}
function renderTabs(){const current=$('#filter').value;$('#categoryTabs').innerHTML=['',...cats].map((c,i)=>`<button type="button" class="category-tab ${current===c?'active':''}" aria-pressed="${current===c}" data-cat="${esc(c)}"><span aria-hidden="true">${['✦','🍲','🥣','🥐','🥪','🥗','🫙','＋'][i]}</span>${esc(c||'Všechny recepty')}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{$('#filter').value=b.dataset.cat;render()})}
function openEditor(r){editing=r?.id||null;$('#recipeForm').reset();draftPhotos=[...(r?.photos||[])];draftScan=r?.scan||'';for(const k of ['title','ingredients','steps','notes','source'])$('#'+k).value=r?.[k]||'';$('#servings').value=r?.servings||4;$('#category').value=r?.category||cats[0];$('#editorTitle').textContent=r?'Upravit recept':'Nový recept';$('#scanStatus').textContent='';$('#saveStatus').textContent='';$('#rawText').value=r?.raw||'';$('#rawDetails').hidden=!r?.raw;renderPhotos();$('#editor').showModal()}
function renderPhotos(){$('#photoPreview').innerHTML=draftPhotos.map((p,i)=>`<div class="photowrap"><img src="${esc(p)}" alt="Fotka jídla ${i+1}"><button type="button" data-photo="${i}" aria-label="Odebrat fotku">✕</button></div>`).join('');document.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>{draftPhotos.splice(Number(b.dataset.photo),1);renderPhotos()})}
async function photo(file,max=1600,quality=.82){if(file.size>30*1024*1024)throw Error('Fotka je příliš velká. Vyber soubor do 30 MB.');return new Promise((resolve,reject)=>{const im=new Image(),url=URL.createObjectURL(file);im.onload=()=>{try{const ratio=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=im.width*ratio;c.height=im.height*ratio;c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',quality))}catch(e){reject(e)}finally{URL.revokeObjectURL(url)}};im.onerror=()=>{URL.revokeObjectURL(url);reject(Error('Fotku nelze otevřít. Zkus JPG nebo PNG.'))};im.src=url})}
$('#photosInput').onchange=async e=>{busy=true;$('#saveButton').disabled=true;try{for(const f of e.target.files)draftPhotos.push(await photo(f));renderPhotos()}catch(e){$('#saveStatus').textContent=e.message}finally{busy=false;$('#saveButton').disabled=false;e.target.value=''}};
$('#recipeForm').onsubmit=async e=>{e.preventDefault();if(busy)return;const r={id:editing||crypto.randomUUID(),updated:Date.now(),photos:draftPhotos,scan:draftScan,raw:$('#rawText').value,servings:Number($('#servings').value),category:$('#category').value};for(const k of ['title','ingredients','steps','notes','source'])r[k]=$('#'+k).value.trim();if(!r.title||!r.ingredients||!r.steps){$('#saveStatus').textContent='Vyplň název, suroviny a postup.';return}$('#saveButton').disabled=true;try{await tx('readwrite',s=>s.put(r));await refresh();$('#editor').close();if($('#detail').open)showDetail(r.id);toast('Recept je uložený.')}catch(e){$('#saveStatus').textContent='Recept se nepodařilo uložit. Může být plné úložiště. Zkus méně fotek a vytvoř zálohu.'}finally{$('#saveButton').disabled=false}};
function scaled(line,factor){return line.replace(/^(\s*)(\d+(?:[.,]\d+)?)(\s|$)/,(_,space,n,end)=>space+String(Math.round(Number(n.replace(',','.'))*factor*100)/100).replace('.',',')+end)}
function ingredients(r,n){$('#ingredientList').innerHTML=r.ingredients.split('\n').filter(x=>x.trim()).map(x=>`<label class="checkline"><input type="checkbox"><span>${esc(scaled(x,n/r.servings))}</span></label>`).join('')}
function showDetail(id){const r=recipes.find(x=>x.id===id);if(!r)return;selected=id;$('#detailContent').innerHTML=`<span class="meta">${esc(r.category)}</span><h1>${esc(r.title)}</h1><div class="photos">${r.photos.map(p=>`<a href="${esc(p)}" target="_blank" rel="noopener"><img src="${esc(p)}" alt="Fotografie ${esc(r.title)}"></a>`).join('')}</div><div class="recipe-columns"><section class="ingredient-panel"><h3><span class="section-number">01</span> Suroviny</h3><label class="portion">Porce<input id="portionCount" type="number" min="1" max="1000" value="${r.servings}"></label><p class="storage-note">Přepočítají se desetinná a celá čísla na začátku řádku. Zlomky, rozsahy a množství uvnitř řádku uprav ručně.</p><div id="ingredientList"></div></section><section class="method-panel"><h3><span class="section-number">02</span> Postup</h3><div class="step">${esc(r.steps)}</div></section></div>${r.notes?`<h3>Moje poznámky</h3><div class="notes">${esc(r.notes)}</div>`:''}${r.source?`<p>Zdroj: ${esc(r.source)}</p>`:''}${r.scan?`<details><summary>Původní fotka receptu</summary><img src="${esc(r.scan)}" alt="Původní recept" style="width:100%;margin-top:16px"></details>`:''}`;ingredients(r,r.servings);$('#portionCount').oninput=e=>{const n=Number(e.target.value);if(n>=1&&n<=1000)ingredients(r,n)};if(!$('#detail').open)$('#detail').showModal()}
$('#editRecipe').onclick=()=>openEditor(recipes.find(r=>r.id===selected));$('#deleteRecipe').onclick=async()=>{if(!confirm('Opravdu smazat tento recept včetně fotek?'))return;try{await tx('readwrite',s=>s.delete(selected));await refresh();$('#detail').close();toast('Recept byl smazán.')}catch{toast('Smazání se nezdařilo.')}};
function loadOCR(){if(window.Tesseract)return Promise.resolve();return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js';s.onload=resolve;s.onerror=()=>{s.remove();reject(Error('Přepis se nepodařilo načíst. Zkontroluj internet a zkus to znovu.'))};document.head.append(s)})}
function splitRecipe(text){const lines=text.split('\n').map(x=>x.trim()).filter(Boolean),title=lines.shift()||'',ix=lines.findIndex(x=>/^(postup|příprava|pracovní postup)\s*[:.]?$/i.test(x));let ingredients='',steps='';if(ix>=0){ingredients=lines.slice(0,ix).filter(x=>!/^(suroviny|ingredience)\s*: ?$/i.test(x)).join('\n');steps=lines.slice(ix+1).join('\n')}else{steps=lines.join('\n')}return {title,ingredients,steps}}
$('#scanInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(($('#title').value||$('#steps').value||$('#ingredients').value)&&!confirm('Přepis nahradí aktuální název, suroviny a postup v rozepsaném receptu. Pokračovat?')){e.target.value='';return}busy=true;$('#saveButton').disabled=true;e.target.disabled=true;let worker;try{$('#scanStatus').textContent='Připravuji fotografii…';const data=await photo(f,2400,.93);await loadOCR();worker=await Tesseract.createWorker('ces',1,{logger:m=>{$('#scanStatus').textContent=m.status==='recognizing text'?`Čtu recept… ${Math.round(m.progress*100)} %`:'Načítám české rozpoznávání…'}});const result=await worker.recognize(data);const text=result.data.text.trim();if(!text)throw Error('Text se nepodařilo přečíst. Zkus ostřejší fotku.');const fields=splitRecipe(text);draftScan=data;$('#rawText').value=text;$('#rawDetails').hidden=false;for(const k of ['title','ingredients','steps'])$('#'+k).value=fields[k];$('#scanStatus').textContent='Hotovo. Zkontroluj text a množství. Pokud chyběly nadpisy, rozděl suroviny a postup ručně.'}catch(err){$('#scanStatus').textContent=err.message||'Přepis selhal. Zkus to znovu nebo vlož text ručně.'}finally{if(worker)await worker.terminate();busy=false;$('#saveButton').disabled=false;e.target.disabled=false;e.target.value=''}};
$('#export').onclick=()=>{const data=JSON.stringify({format:'moje-kucharka',version:1,recipes},null,2),url=URL.createObjectURL(new Blob([data],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`moje-kucharka-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);$('#backupStatus').textContent='Záloha je připravena ke stažení.'};
function valid(r){return r&&typeof r.id==='string'&&r.id.length<200&&['title','ingredients','steps','notes','source'].every(k=>typeof r[k]==='string')&&Number.isFinite(r.servings)&&r.servings>=1&&r.servings<=1000&&Number.isFinite(r.updated)&&cats.includes(r.category)&&Array.isArray(r.photos)&&r.photos.every(x=>typeof x==='string'&&/^data:image\/(jpeg|png|webp);base64,/.test(x))&&(!r.scan||/^data:image\/(jpeg|png|webp);base64,/.test(r.scan))}
$('#import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const b=JSON.parse(await f.text());if(b.format!=='moje-kucharka'||b.version!==1||!Array.isArray(b.recipes)||!b.recipes.every(valid))throw Error('Tento soubor není platná záloha kuchařky.');if(!confirm(`Obnovit ${b.recipes.length} receptů? Recepty se stejným ID budou nahrazeny.`))return;await tx('readwrite',s=>{b.recipes.forEach(r=>s.put(r))});await refresh();$('#backupStatus').textContent=`Obnoveno ${b.recipes.length} receptů.`}catch(err){$('#backupStatus').textContent=err.message||'Obnova se nezdařila.'}finally{e.target.value=''}};
$('#newRecipe').onclick=()=>openEditor();$('#scanNew').onclick=()=>{openEditor();$('#scanInput').click()};$('#backupOpen').onclick=()=>$('#backup').showModal();$('#search').oninput=render;$('#filter').onchange=render;document.querySelectorAll('.close').forEach(b=>b.onclick=()=>{if(b.closest('dialog').id==='editor'&&busy){toast('Počkej na dokončení zpracování fotky.');return}b.closest('dialog').close()});$('#editor').addEventListener('cancel',e=>{if(busy)e.preventDefault()});cats.forEach(c=>{$('#category').add(new Option(c,c));$('#filter').add(new Option(c,c))});
const req=indexedDB.open('moje-kucharka',1);req.onupgradeneeded=()=>req.result.createObjectStore('recipes',{keyPath:'id'});req.onsuccess=async()=>{db=req.result;await refresh()};req.onerror=()=>{$('#recipes').textContent='Úložiště není dostupné. Otevři kuchařku v běžném okně prohlížeče a povol ukládání dat.';$('#newRecipe').disabled=true;$('#scanNew').disabled=true};
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'search_recipes',description:'Vyhledá uložené recepty podle názvu nebo surovin.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async input=>{if(typeof input.query!=='string')throw Error('query musí být text');if(!db)throw Error('Kuchařka se načítá');const q=input.query.toLocaleLowerCase('cs');return recipes.filter(r=>(r.title+' '+r.ingredients).toLocaleLowerCase('cs').includes(q)).map(r=>({id:r.id,title:r.title,ingredients:r.ingredients,steps:r.steps}))}})).catch(()=>{})}catch{}}
